### ISSUE TITLE
Two fixes

### ISSUE THREAD

**Issue by DebugDax** [santosderek/Imgur-To-Folder#1]
During setup there are two issues that exists in the source files.

1) config.py
The 'download_folder_path' has an 'r' character sitting outside the quotes

2) setup.py
It's set to look for 'imgurtofolder' when the source folder is 'ImgurToFolder'

**Comment by santosderek** [comment]
Thank you for letting me know! I just fixed the repository and have tested it on Ubuntu and Windows. There was a cross-platform issue that I needed to fix. 

The 'r' character outside of the quotes is to register the string as a raw-string. This escapes backslashes for easier use when using folder paths within python. For the time being I'm going to keep this feature in but let me know if it presents a problem!
