### ISSUE TITLE
unable to change target folder

### ISSUE THREAD

**Issue by Felixoo7** [santosderek/Imgur-To-Folder#10]
Probably I am just dumb and hopefully this project isn't totally dead.

Attempting to change the target directory I used the command 
imgurtofolder --folder FOLDER_PATH_HERE
![image](https://user-images.githubusercontent.com/5273042/65367374-1f97f180-dbf6-11e9-9ffa-5e7ea563dcc4.png)

After doing this I attempt to download an image and it always puts it into the IFT main directory. What am I doing wrong?

**Comment by santosderek** [comment]
Hello! 

`-f` only changes the target directory for that process of the command. To change the default target directory, you'll have to change the `config.json` before installing. 

So the command should look like `itf -f C:\Some\Path\Here url1 url2 url3`

I'm working on a new update to Imgur-To-Folder, and will have an argument to change the default download path without reinstalling.

**Comment by Felixoo7** [comment]
I knew it was an ID10T error. I didn't think to try the command in line. Thanks it is working just fine now.
