### ISSUE TITLE
Imgur Unable to Authenticate ImgurToFolder

### ISSUE THREAD

**Issue by vmpas** [santosderek/Imgur-To-Folder#5]
I'm not sure if this is an issue with Imgur or not, but I figure this is the best place to start.  

I tried to download from my favorites and received the message about going to https://api.imgur.com/oauth2/authorize?client_id=6641d8eb78d0d32 &response_type=token&state=authorizing

I was brought to the Login Screen, logged in and then was brought to where I click "Allow" and then instead of being brought to the front page of Imgur as the directions state, I am brought to a white screen with the following...error?:{"data":{"error":"No client id supplied","request":"\/oauth2\/authorize","method":"POST"},"success":false,"status":400}

It sounds like to me that this is indicating an incorrect piece of information, but I am not sure what.  

Thanks in advance.

**Comment by santosderek** [comment]
Hello! 

Before installing the script, did you enter your client id received from imgur within the config.json? 

The error message says ```"error":"No client id supplied"``` which I'm assuming is from an empty json configuration. The script should pull the client_id from the json file within, ```imgur-to-folder/imgurtofolder/config.json```.

**Comment by vmpas** [comment]
Yes.  I double checked the config file and both the Client ID and Client Secret are present.  
I then rewrote the file and reran the setup.  This fixed it.  Not sure what happened.
